### ISSUE TITLE
Error when building on ARMHF

### ISSUE THREAD

**Issue by sbfreddie** [nohal/wmm_pi#5]
Nohal:
I am trying to build this plugin on the CubieTruck under Qbee-X (Ubuntu 12.04.5).
I am getting these errors:[ 86%] Built target wmm-i18n
Scanning dependencies of target wmm_pi
[ 86%] Building CXX object plugins/wmm_pi/CMakeFiles/wmm_pi.dir/src/wmm_pi.cpp.o
/home/cubie/GitOpenCPN/OpenCPN/plugins/wmm_pi/src/wmm_pi.cpp: In member function ‘virtual int wmm_pi::GetPlugInVersionMajor()’:
/home/cubie/GitOpenCPN/OpenCPN/plugins/wmm_pi/src/wmm_pi.cpp:231:12: error: ‘PLUGIN_VERSION_MAJOR’ was not declared in this scope
/home/cubie/GitOpenCPN/OpenCPN/plugins/wmm_pi/src/wmm_pi.cpp: In member function ‘virtual int wmm_pi::GetPlugInVersionMinor()’:
/home/cubie/GitOpenCPN/OpenCPN/plugins/wmm_pi/src/wmm_pi.cpp:236:12: error: ‘PLUGIN_VERSION_MINOR’ was not declared in this scope
/home/cubie/GitOpenCPN/OpenCPN/plugins/wmm_pi/src/wmm_pi.cpp:237:1: warning: control reaches end of non-void function [-Wreturn-type]
/home/cubie/GitOpenCPN/OpenCPN/plugins/wmm_pi/src/wmm_pi.cpp: In member function ‘virtual int wmm_pi::GetPlugInVersionMajor()’:
/home/cubie/GitOpenCPN/OpenCPN/plugins/wmm_pi/src/wmm_pi.cpp:232:1: warning: control reaches end of non-void function [-Wreturn-type]
make[2]: **\* [plugins/wmm_pi/CMakeFiles/wmm_pi.dir/src/wmm_pi.cpp.o] Error 1
make[1]: **\* [plugins/wmm_pi/CMakeFiles/wmm_pi.dir/all] Error 2
make: **\* [all] Error 2

Any idea what I am doing wrong?

Thanks,
Freddie

**Comment by nohal** [comment]
I suppose you are building the plugin inside OpenCPN tree. The default now is to build the plugin separately, when cmake configure step generates src/version.h containing the definitions you are missing.
Updated the README to reflect this change.
If you want to just get going as you are, create the /home/cubie/GitOpenCPN/OpenCPN/plugins/wmm_pi/src/version.h file manually, containing

```
#define PLUGIN_VERSION_MAJOR 0
#define PLUGIN_VERSION_MINOR 9
#define PLUGIN_VERSION_DATE ""
```

**Comment by sbfreddie** [comment]
On Oct 15, 2014, at 8:06 AM, Pavel Kalian notifications@github.com wrote:

> I suppose you are building the plugin inside OpenCPN tree. The default now is to build the plugin separately, when cmake configure step generates src/version.h containing the definitions you are missing.
> Updated the README to reflect this change.
> If you want to just get going as you are, create the /home/cubie/GitOpenCPN/OpenCPN/plugins/wmm_pi/src/version.h file manually, containing
> 
> #define PLUGIN_VERSION_MAJOR 0
> #define PLUGIN_VERSION_MINOR 9
> #define PLUGIN_VERSION_DATE ""
> —
> Reply to this email directly or view it on GitHub.
> 
> Thanks Pavel

Freddie=
