### ISSUE TITLE
Build errors Win32-XP > jsonval.cpp: Concatenating wide "%" with narrow "I64"

### ISSUE THREAD

**Issue by Hakansv** [nohal/wmm_pi#8]
Pavel.
Prev. Win bug now ok, thanks.
One new issue after WX 3.0.2  (Never seen this before)
The same error for "cmake" and VC2010
(parts of) Build log:
------ Build started: Project: wmm_pi, Configuration: Release Win32 ------
  Microsoft (R) 32-bit C/C++ Optimizing Compiler Version 16.00.40219.01 for 80x86
  Copyright (C) Microsoft Corporation.  All rights reserved.

  cl /c /I"C:\wxWidgets-3.0.2\lib\vc_dll\mswu" /I"C:\wxWidgets-3.0.2\include" /IC:\Builds\OpenCPN\OpenCPN\include /IC:\Builds\OpenCPN\OpenCPN\src /IC:\Builds\OpenCPN\OpenCPN\buildwin\crashrpt /IC:\Builds\OpenCPN\OpenCPN\src\nmea0183 /IC:\Builds\OpenCPN\OpenCPN\src\mygdal /IC:\Builds\OpenCPN\OpenCPN\src\garmin\jeeps /IC:\Builds\OpenCPN\OpenCPN\src\texcmp\lz4 /IC:\Builds\OpenCPN\OpenCPN\src\texcmp\squish /IC:\Builds\OpenCPN\OpenCPN\plugins\wmm_pi\include /IC:\Builds\OpenCPN\OpenCPN\plugins\wmm_pi\src /W3 /WX- /O2 /Ob2 /Oy- /D WIN32 /D _WINDOWS /D NDEBUG /D ocpnUSE_GL /D USE_GLU_TESS /D WXUSINGDLL /D UNICODE /D _UNICODE /D OCPN_USE_CRASHRPT /D __MSVC__ /D _CRT_NONSTDC_NO_DEPRECATE /D _CRT_SECURE_NO_DEPRECATE /D PSAPI_VERSION=1 /D TIXML_USE_STL /D USE_S57 /D USE_GARMINHOST /D __WIN32__ /D "CMAKE_INTDIR=\"Release\"" /D wmm_pi_EXPORTS /D _WINDLL /D _UNICODE /D UNICODE /Gm- /EHa /MD /GS /fp:precise /Zc:wchar_t /Zc:forScope /GR /Fo"wmm_pi.dir\Release\" /Fd"wmm_pi.dir\Release\vc100.pdb" /Gd /TP /analyze- /errorReport:prompt ......\plugins\wmm_pi\src\jsonval.cpp

  jsonval.cpp
......\plugins\wmm_pi\src\jsonval.cpp(965): error C2308: concatenating mismatched strings
          Concatenating wide "%" with narrow "I64"
......\plugins\wmm_pi\src\jsonval.cpp(973): error C2308: concatenating mismatched strings
          Concatenating wide "%" with narrow "I64"

**Comment by nohal** [comment]
Hakan...
We can expect these - wx3, for good, abandoned their own string implementation and switched to std::string internally
